baseurl = "/"
languageCode = "en-us"
title = "Austin Gilmour"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 5

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Austin Gilmour"
	description = "A portfolio site utilizing Hugo"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "I'm **Austin Gilmour**<br> an effective **project manager**<br> passionate **customer support specialist**<br> and skilled **developer**"
		# The icons will be shown if you enter your username
		twitter = "gilmoursa"
		github = "gilmoursa"
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = "https://www.linkedin.com/in/austingilmour"

		copyright = [
			"&copy; Austin Gilmour",
		]


	[params.about]
		hide  = false
		title = "Creating Responsive WordPress sites for some of New York's largest non-profits."
		content = "In my most recent role, I worked as a project manager for a small branding agency in Brooklyn focusing on non-profits. I managed a remote team of developers to create responsive WordPress sites for some of New York's largest non-profits under budget and ahead of schedule. I'm interested in expanding my horizons and working in a more customer-facing support role."


	[params.portfolio]
		hide  = false
		title = "Web Development Portfolio"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "http://www.citybarjusticecenter.org/"
			thumb = "thumbs/01.jpg"
			title = "City Bar Justice Center."
			description = "A responsive WordPress site leveraging advanced custom fields, custom post types, and multiple blogs."

		[[params.portfolio.gallery]]
			image = "http://bwiny.org/"
			thumb = "thumbs/02.jpg"
			title = "Brooklyn Workforce Innovations."
			description = "A responsive WordPress site with a custom theme and heavy use of advanced custom fields."

		[[params.portfolio.gallery]]
			image = "https://www.nywf.org/"
			thumb = "thumbs/03.jpg"
			title = "New York Women's Foundation."
			description = "A responsive WordPress site making use of extensive search and filtering."

		[[params.portfolio.gallery]]
			image = "https://mshp.mountsinai.org/"
			thumb = "thumbs/04.jpg"
			title = "Mount Sinai Health Partners."
			description = "A responsive WordPress site connected to OKTA's single sign-on service."

		[[params.portfolio.gallery]]
			image = "https://www.cucs.org/"
			thumb = "thumbs/05.jpg"
			title = "Center for Urban Community Services."
			description = "A WordPress site with an interactive job board and custom post types."

		[[params.portfolio.gallery]]
			image = "http://winnyc.org/"
			thumb = "thumbs/06.jpg"
			title = "Women In Need."
			description = "A responsive WordPress site with advanced custom fields and Blackbaud API integration."

	[params.recentposts]
		hide  = true
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Interested in hiring me? Feel free to reach out using the contact form below."

		address = [
			"Pulaski St",
			"Brooklyn, NY 11206",
			"United States"
		]
		phone = "(727) 251-3154"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "gilmoursa@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
    name = "About"
    url  = "about"
    weight = 5
